FROM 695807466803.dkr.ecr.eu-west-1.amazonaws.com/dockerproductionaws/microtrader-base:latest
LABEL application.component=microtrader-quote
HEALTHCHECK --interval=3s --retries=20 CMD curl -fs http://localhost:${HTTP_PORT:-35000}/${HTTP_ROOT}

# Copy application artefacts
ARG app_version
LABEL application.version=${app_version}
COPY build/jars/microtrader-quote-${app_version}-fat.jar /app/app.jar